version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    volumes:
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d/
      - ./laravel/public:/var/www/laravel/public
    ports:
      - 80:80
    links:
      - phpfpm
    depends_on:
      - phpfpm
  phpfpm:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./laravel:/var/www/laravel
      - ./:/var/www/html
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=kekkon
      - DB_USERNAME=root
      - DB_PASSWORD=pass
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=kekkon
